#!/usr/bin/env ansible-playbook
---
- name: Readynas Playbook
  hosts: readynas

  tasks:
    - name: Disable Samba from providing multicast DNS
      lineinfile: 
        name: /etc/frontview/samba/smb.conf.defaults
        state: present
        regexp: "^multicast dns register"
        line: "multicast dns register = no"
      notify: restart samba

    - name: Enable Samba syslog
      lineinfile: 
        name: /etc/frontview/samba/smb.conf.defaults
        state: present
        regexp: "^syslog"
        line: "syslog = 1"
      notify: restart avahi-daemon
    - name: Disable avahi workstation publishers
      lineinfile: 
        name: /etc/avahi/avahi-daemon.conf
        insertafter: "^[publish]"
        state: present
        regexp: "^publish-workstation="
        line: "^publish-workstation=no"
      notify: restart avahi-daemon
    - name: Add Avahi based SMB service
      template:
        src: samba.service.j2
        dest: /etc/avahi/services/samba.service
        owner: root
        group: root
        mode: 0444

handlers:
    - name: restart samba
      service:
        name: smb
        state: restarted
    - name: restart avahi-daemon
      service:
        name: avahi-daemon
        state: restarted
